//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRANSLATION3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRANSLATION3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _redsquaregames {
            get {
                object obj = ResourceManager.GetObject("_redsquaregames", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///
        ///480 500 200
        ///800 300 200
        ///
        ///PUSH 6 NONE 1
        ///.
        /// </summary>
        internal static string classic0 {
            get {
                return ResourceManager.GetString("classic0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 2
        ///
        ///640 500 200
        ///320 400 200
        ///960 300 200
        ///640 200 200
        ///
        ///PUSH 10 NONE 3
        ///PUSH 6 NONE 2
        ///.
        /// </summary>
        internal static string classic1 {
            get {
                return ResourceManager.GetString("classic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 2
        ///
        ///320 500 200
        ///960 350 200
        ///320 200 200
        ///1080 200 200
        ///
        ///HORZ_MAGNET 6 NONE 3
        ///GRAV_RED 6 NONE 2
        ///.
        /// </summary>
        internal static string classic10 {
            get {
                return ResourceManager.GetString("classic10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 3
        ///
        ///440 600 200
        ///320 300 200
        ///840 400 200
        ///1000 200 200
        ///
        ///SHOVE 6 NONE 3
        ///HORZ_MAGNET 6 NONE 1
        ///DECAY 10 NONE 2
        ///.
        /// </summary>
        internal static string classic11 {
            get {
                return ResourceManager.GetString("classic11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///
        ///320 500 200
        ///960 300 200
        ///640 200 200
        ///
        ///SHOVE 6 NONE 1
        ///HORZ_MAGNET 6 NONE 2
        ///.
        /// </summary>
        internal static string classic12 {
            get {
                return ResourceManager.GetString("classic12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///
        ///280 400 200
        ///640 500 200
        ///1000 200 200
        ///
        ///GRAV_RED 10 NONE 1
        ///GRAV_INC 10 NONE 2
        ///.
        /// </summary>
        internal static string classic13 {
            get {
                return ResourceManager.GetString("classic13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 4
        ///
        ///280 200 200
        ///520 300 200
        ///760 400 200
        ///1000 500 200
        ///1000 200 200
        ///
        ///GRAV_INC 10 NONE 1
        ///GRAV_INC 10 NONE 2
        ///GRAV_INC 10 NONE 3
        ///HORZ_MAGNET 6 NONE 4
        ///.
        /// </summary>
        internal static string classic14 {
            get {
                return ResourceManager.GetString("classic14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 1
        ///
        ///280 500 300
        ///640 300 200
        ///1000 200 200
        ///
        ///HORZ_MAGNET 14 NONE 2
        ///.
        /// </summary>
        internal static string classic15 {
            get {
                return ResourceManager.GetString("classic15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///
        ///320 400 200
        ///960 400 200
        ///
        ///MOVE -10 NONE 1
        ///.
        /// </summary>
        internal static string classic2 {
            get {
                return ResourceManager.GetString("classic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 3
        ///
        ///640 500 200
        ///640 200 200
        ///320 300 200
        ///960 300 200
        ///
        ///PUSH 10 NONE 2
        ///MOVE 6 NONE 3
        ///PUSH 10 NONE 1
        ///.
        /// </summary>
        internal static string classic3 {
            get {
                return ResourceManager.GetString("classic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///
        ///320 500 200
        ///960 300 400
        ///
        ///DECAY 12 NONE 1
        ///.
        /// </summary>
        internal static string classic4 {
            get {
                return ResourceManager.GetString("classic4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 1
        ///
        ///640 500 200
        ///640 200 200
        ///280 300 140
        ///880 400 140
        ///
        ///FLEE 6 NONE 1
        ///.
        /// </summary>
        internal static string classic5 {
            get {
                return ResourceManager.GetString("classic5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 3
        ///
        ///640 500 200
        ///640 350 200
        ///640 200 200
        ///1080 350 140
        ///200 350 140
        ///
        ///PULL 4 NONE 3
        ///PUSH 4 NONE 4
        ///GRAV_RED 10 NONE 2
        ///.
        /// </summary>
        internal static string classic6 {
            get {
                return ResourceManager.GetString("classic6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 3
        ///
        ///640 500 200
        ///280 350 200
        ///1000 350 200
        ///640 200 140
        ///
        ///SHOVE 8 NONE 1
        ///SPREAD 6 NONE 2
        ///FLEE 10 NONE 3
        ///.
        /// </summary>
        internal static string classic7 {
            get {
                return ResourceManager.GetString("classic7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 3
        ///
        ///480 350 200
        ///640 500 200
        ///960 500 200
        ///320 500 200
        ///800 350 200
        ///640 200 200
        ///
        ///PUSH 8 NONE 4
        ///SPREAD 6 NONE 5
        ///HORZ_MAGNET 10 NONE 2
        ///.
        /// </summary>
        internal static string classic8 {
            get {
                return ResourceManager.GetString("classic8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 4
        ///
        ///280 200 200
        ///1000 300 200
        ///640 400 200
        ///280 500 200
        ///1000 600 200
        ///
        ///SHOVE 8 NONE 3
        ///DECAY 6 NONE 1
        ///HORZ_MAGNET 10 NONE 2
        ///SPREAD 10 NONE 4
        ///.
        /// </summary>
        internal static string classic9 {
            get {
                return ResourceManager.GetString("classic9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lowercase_vigilant_2_boldface {
            get {
                object obj = ResourceManager.GetObject("lowercase_vigilant_2_boldface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///The Ropes, pt. I
        ///1000 1000 200
        ///1000 800 200
        ///Jump and land on the sentry.
        ///PUSH 6 NONE 1
        ///.
        /// </summary>
        internal static string main0 {
            get {
                return ResourceManager.GetString("main0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///The Ropes, pt. II
        ///1000 1000 200
        ///1000 1200 200
        ///Drop and land on the sentry.
        ///PUSH 6 NONE 1
        ///.
        /// </summary>
        internal static string main1 {
            get {
                return ResourceManager.GetString("main1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///Defying Gravity
        ///1000 1000 200
        ///800 700 200
        ///800 1400 200
        ///The camera has a zoom toggle.
        ///GRAV_RED 10 NONE 1
        ///GRAV_INC -6 NONE 2
        ///.
        /// </summary>
        internal static string main10 {
            get {
                return ResourceManager.GetString("main10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 4
        ///The Nest
        ///1000 1000 200
        ///600 600 200
        ///600 800 200
        ///600 1000 200
        ///600 1200 200
        ///600 1400 200
        ///1000 600 200
        ///1000 800 200
        ///1000 1200 200
        ///1000 1400 200
        ///1400 600 200
        ///1400 800 200
        ///1400 1000 200
        ///1400 1200 200
        ///1400 1400 200
        ///
        ///SPAWN 10 SPAWN 1
        ///SPAWN 10 SPAWN 5
        ///SPAWN -10 SPAWN 10
        ///SPAWN -10 SPAWN 14
        ///.
        /// </summary>
        internal static string main100 {
            get {
                return ResourceManager.GetString("main100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 1
        ///The Invisible Hand
        ///1000 1000 300
        ///1500 800 300
        ///2000 600 300
        ///2500 400 300
        ///
        ///HORZ_MAGNET 14 NONE 3
        ///.
        /// </summary>
        internal static string main11 {
            get {
                return ResourceManager.GetString("main11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///Push &amp; Pull ++
        ///1000 1000 200
        ///1400 1000 200
        ///600 1000 200
        ///Teleport jumps can be chained.
        ///EXPAND -14 NONE 1
        ///HORZ_MAGNET 10 NONE 2
        ///.
        /// </summary>
        internal static string main12 {
            get {
                return ResourceManager.GetString("main12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 5
        ///The Great Dictator
        ///1000 1000 200
        ///800 800 100
        ///800 1200 100
        ///1200 800 100
        ///1200 1200 100
        ///1400 600 100
        ///1400 200 100
        ///1600 400 200
        ///1800 600 100
        ///1800 200 100
        ///1000 400 300
        ///1600 1000 300
        ///If you know, you know ;P
        ///PULL 8 NONE 10
        ///PULL -8 NONE 11
        ///NECROMANCER 4 NONE 7
        ///EXPAND 8 NONE 1
        ///EXPAND -8 NONE 8
        ///.
        /// </summary>
        internal static string main13 {
            get {
                return ResourceManager.GetString("main13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 6
        ///As Above, So Below
        ///1000 1000 200
        ///1000 800 200
        ///1000 600 200
        ///1000 400 200
        ///1000 1200 200
        ///1000 1400 200
        ///1000 1600 200
        ///The clue is in the order
        ///FLEE 6 RANDOM 1
        ///FLEE 6 RANDOM 4
        ///FLEE 6 RANDOM 5
        ///FLEE 6 RANDOM 6
        ///FLEE 6 RANDOM 3
        ///FLEE 6 RANDOM 2
        ///.
        /// </summary>
        internal static string main14 {
            get {
                return ResourceManager.GetString("main14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 3
        ///Jules Verne
        ///1000 1000 150
        ///1000 14000 150
        ///1000 14200 150
        ///1000 14400 150
        ///925 4000 100
        ///1075 4000 100
        ///-1200 8000 3500
        ///2400 8000 3500
        ///-400 12000 3500
        ///3200 12000 3500
        ///Journey to the Center of the Earth
        ///GRAV_RED 6 NONE 1
        ///GRAV_INC -12 NONE 2
        ///GRAV_RED 6 NONE 3
        ///.
        /// </summary>
        internal static string main15 {
            get {
                return ResourceManager.GetString("main15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 4
        ///Splitsville
        ///1000 1000 25
        ///1000 800 25
        ///1000 1200 25
        ///1200 1000 25
        ///800 1000 25
        ///&apos;Esposas&apos;
        ///GOD 14 PUSH 1
        ///GOD -14 RANDOM 2
        ///MOVE 14 RANDOM 4
        ///MOVE -14 RANDOM 3
        ///.
        /// </summary>
        internal static string main16 {
            get {
                return ResourceManager.GetString("main16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///The Ropes, pt. III
        ///1000 1000 200
        ///1300 1000 200
        ///The player can move side to side.
        ///PUSH 6 NONE 1
        ///.
        /// </summary>
        internal static string main2 {
            get {
                return ResourceManager.GetString("main2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///Continental Drift
        ///1000 1000 200
        ///700 1000 200
        ///700 800 200
        ///Look alive!
        ///EXPAND 10 NONE 1
        ///PUSH -6 NONE 2
        ///.
        /// </summary>
        internal static string main20 {
            get {
                return ResourceManager.GetString("main20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 9
        ///Exploration, pt. I
        ///0 1000 100
        ///0 1200 200
        ///-3000 1000 200
        ///-3000 1200 200
        ///3000 1000 200
        ///3000 1200 200
        ///0 -2000 200
        ///0 -1800 200
        ///0 4000 200
        ///0 4200 200
        ///Balance of powers
        ///GRAV_RED 10 NONE 1
        ///GRAV_RED 10 NONE 2
        ///GRAV_RED 10 NONE 4
        ///GRAV_RED 10 NONE 6
        ///GRAV_RED 10 NONE 8
        ///GRAV_INC 10 NONE 3
        ///GRAV_INC 10 NONE 5
        ///GRAV_INC 10 NONE 7
        ///GRAV_INC 10 NONE 9
        ///.
        /// </summary>
        internal static string main25 {
            get {
                return ResourceManager.GetString("main25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///The Ropes, pt. IV
        ///1000 1000 200
        ///1600 1000 200
        ///Teleportation!
        ///PUSH 6 NONE 1
        ///.
        /// </summary>
        internal static string main3 {
            get {
                return ResourceManager.GetString("main3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 6
        ///Conveyor Belt
        ///1000 700 100
        ///1000 1000 200
        ///800 1000 200
        ///2800 1000 200
        ///2800 1300 200
        ///800 1300 200
        ///2600 1300 200
        ///Sentries can create dead zones if their powers cancel out.
        ///MOVE 6 NONE 1
        ///SHOVE 10 NONE 2
        ///SHOVE -10 NONE 3
        ///SHOVE -10 NONE 4
        ///SHOVE 10 NONE 5
        ///MOVE -6 NONE 6
        ///.
        /// </summary>
        internal static string main34 {
            get {
                return ResourceManager.GetString("main34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 2
        ///Line of Sight
        ///1000 1000 100
        ///600 1000 250
        ///1400 1000 250
        ///200 1000 250
        ///1800 1000 250
        ///Fleeing sentries cannot flee to the starting platform.
        ///FLEE 10 NONE 1
        ///FLEE -12 NONE 2
        ///.
        /// </summary>
        internal static string main35 {
            get {
                return ResourceManager.GetString("main35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 3
        ///The Pull
        ///1000 -1200 200
        ///1400 -1100 200
        ///1800 -1100 200
        ///2200 -1200 200
        ///2600 -1300 200
        ///3000 -1300 200
        ///3400 -1400 200
        ///3800 -1500 200
        ///4200 -1500 200
        ///4600 -1600 200
        ///An even number of pink sentries create dead zones.
        ///HORZ_MAGNET -10 NONE 3
        ///HORZ_MAGNET -10 NONE 6
        ///HORZ_MAGNET -10 NONE 9
        ///.
        /// </summary>
        internal static string main36 {
            get {
                return ResourceManager.GetString("main36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 8
        ///Break The Wheel
        ///1000 1000 50
        ///500 1000 150
        ///1500 1000 150
        ///1000 500 150
        ///1000 1500 150
        ///625 625 150
        ///1375 625 150
        ///625 1375 150
        ///1375 1375 150
        ///Keep the net gravity in mind.
        ///GRAV_RED 6 NONE 1
        ///GRAV_RED 8 NONE 2
        ///GRAV_RED 10 NONE 3
        ///GRAV_RED 12 NONE 4
        ///GRAV_INC 6 NONE 5
        ///GRAV_INC 8 NONE 6
        ///GRAV_INC 10 NONE 7
        ///GRAV_INC 12 NONE 8
        ///.
        /// </summary>
        internal static string main37 {
            get {
                return ResourceManager.GetString("main37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///The Springboard
        ///1000 1000 200
        ///700 750 200
        ///700 1250 200
        ///
        ///GRAV_INC 10 NONE 1
        ///GRAV_FLIP 6 NONE 2
        ///.
        /// </summary>
        internal static string main38 {
            get {
                return ResourceManager.GetString("main38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///The Ropes, pt. V
        ///1000 1000 200
        ///1450 1000 200
        ///Different types of sentries have different abilities.
        ///MOVE 6 NONE 1
        ///.
        /// </summary>
        internal static string main4 {
            get {
                return ResourceManager.GetString("main4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///The Ropes, pt. VI
        ///1000 1000 200
        ///800 800 200
        ///1200 1200 200
        ///
        ///PUSH 8 NONE 1
        ///PUSH -8 NONE 2
        ///.
        /// </summary>
        internal static string main5 {
            get {
                return ResourceManager.GetString("main5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 2
        ///On Its Head
        ///1000 1000 100
        ///800 900 200
        ///1200 700 200
        ///1000 600 100
        ///Meet your maker.
        ///PUSH 10 NONE 1
        ///GOD 14 NONE 2
        ///.
        /// </summary>
        internal static string main50 {
            get {
                return ResourceManager.GetString("main50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///The Ropes, pt. VII
        ///1000 1000 200
        ///1300 1000 100
        ///1600 1000 100
        ///Sight-dependent abilities compound when activated simultaneously.
        ///PULL -10 NONE 1
        ///PULL -10 NONE 2
        ///.
        /// </summary>
        internal static string main6 {
            get {
                return ResourceManager.GetString("main6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///The Ropes, pt. VIII
        ///1000 1000 200
        ///1000 650 200
        ///Save and load your position with your motion preserved.
        ///PUSH 6 NONE 1
        ///.
        /// </summary>
        internal static string main7 {
            get {
                return ResourceManager.GetString("main7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 6
        ///Paradise Lost
        ///1000 1000 50
        ///1000 0 300
        ///1000 2000 300
        ///600 1700 100
        ///1400 1700 100
        ///600 300 100
        ///1400 300 100
        ///1000 1300 50
        ///1000 700 50
        ///Did you know that &quot;pandemonium&quot; was coined by John Milton to mean the capital of Hell?
        ///GOD 14 NONE 1
        ///GOD -14 NONE 2
        ///PULL 10 NONE 3
        ///PUSH -10 NONE 4
        ///PUSH 10 NONE 5
        ///PULL -10 NONE 6
        ///.
        /// </summary>
        internal static string main74 {
            get {
                return ResourceManager.GetString("main74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 6
        ///Necromancer&apos;s Curse, pt. I
        ///1000 1000 200
        ///0 1000 200
        ///2000 1000 200
        ///650 1200 100
        ///1350 1200 100
        ///1000 600 250
        ///1000 1400 250
        ///
        ///NECROMANCER 12 NONE 1
        ///NECROMANCER -12 NONE 2
        ///GRAV_INC 6 NONE 3
        ///PULL -14 NONE 4
        ///GRAV_RED 8 NONE 5
        ///GOD -6 NONE 6.
        /// </summary>
        internal static string main75 {
            get {
                return ResourceManager.GetString("main75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 2
        ///Necromancer&apos;s Curse, pt. II
        ///1000 1000 100
        ///500 1000 300
        ///0 1000 100
        ///1500 1000 300
        ///2000 1000 100
        ///0 800 300
        ///500 800 100
        ///1000 800 300
        ///1500 800 100
        ///2000 800 300
        ///0 1200 300
        ///500 1200 100
        ///1000 1200 300
        ///1500 1200 100
        ///2000 1200 300
        ///A matter of priority
        ///SPAWN 12 SPAWN 5
        ///NECROMANCER -10 NONE 14
        ///.
        /// </summary>
        internal static string main76 {
            get {
                return ResourceManager.GetString("main76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 8
        ///Necromancer&apos;s Curse, pt. III
        ///1000 1000 200
        ///500 800 200
        ///1000 800 100
        ///1500 800 200
        ///500 1000 100
        ///1500 1000 100
        ///500 1200 200
        ///1000 1200 100
        ///1500 1200 200
        ///
        ///NECROMANCER 10 NONE 1
        ///NECROMANCER -10 NONE 3
        ///NECROMANCER -10 NONE 6
        ///NECROMANCER 10 NONE 8
        ///EXPAND 8 NONE 2
        ///EXPAND 8 NONE 4
        ///EXPAND -8 NONE 5
        ///EXPAND -8 NONE 7
        ///.
        /// </summary>
        internal static string main77 {
            get {
                return ResourceManager.GetString("main77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///The Ropes, pt. IX
        ///1000 1000 200
        ///1000 1400 200
        ///Some sentries have abilities that do not rely on seeing the player.
        ///GRAV_RED 10 NONE 1
        ///.
        /// </summary>
        internal static string main8 {
            get {
                return ResourceManager.GetString("main8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///The Ropes, pt. X
        ///1000 1000 200
        ///700 1000 100
        ///1200 1150 200
        ///Sentries can alter physics, gravity, the stage, and the game&apos;s reality itself.
        ///PUSH -6 NONE 1
        ///HORZ_MAGNET 8 NONE 2
        ///.
        /// </summary>
        internal static string main9 {
            get {
                return ResourceManager.GetString("main9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mousepointer {
            get {
                object obj = ResourceManager.GetObject("mousepointer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap numbers_vigilant_2_boldface {
            get {
                object obj = ResourceManager.GetObject("numbers_vigilant_2_boldface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap symbols_vigilant_2_boldface {
            get {
                object obj = ResourceManager.GetObject("symbols_vigilant_2_boldface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap symbols2_vigilant_2_boldface {
            get {
                object obj = ResourceManager.GetObject("symbols2_vigilant_2_boldface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap t3logo_664_164 {
            get {
                object obj = ResourceManager.GetObject("t3logo_664_164", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 2
        ///
        ///1000 1000 200
        ///700 1000 200
        ///1300 1000 200
        ///
        ///PUSH 2 NONE 1
        ///NECROMANCER -6 NONE 2
        ///.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uppercase_vigilant_2_boldface {
            get {
                object obj = ResourceManager.GetObject("uppercase_vigilant_2_boldface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
